### ISSUE TITLE
config() called many times on startup

### ISSUE THREAD

**Issue by corbt** [zserge/anvil#20] opened 2015-07-27 16:04 UTC
I need to add a photo-taking activity to my application, and I'm using Anvil for the view. I've just updated to 0.0.9.

I'm trying out the new `config()` functionality (I use my homemade `ref` system in my existing activities) and am running into an issue.

Basically, `config()` function is being called on every user interaction, and even multiple times without any interaction at startup (it seems to be called 4 times at activity startup without any callbacks or calls to `Anvil.render()`). The issue is that in my `config()` function I wire up a `SurfaceView` to a camera instance. When a picture is taken, the config() block is called again (even though the SurfaceView has never disappeared from the screen, or changed in any way, nor any of its parents) and tries to set up the SurfaceView again, which fails because the camera is no longer in the right mode.

I think I can work around this by adding a boolean flag to indicate that the camera has been initialized and then only calling the code in `config` if it hasn't been called before, but my understanding is that `config` should do this itself, and only be called when there has been an actual change to an element or its parents. Is my understanding correct?

**Comment by zserge** [comment] 2015-07-27 16:10
@corbt May I ask you to add some logs to the Anvil's config() binding (see BaseAttrs.java class) and do some debugging?
Basically, yesterday I've played with config in some simple apps (in my new anvil-examples repo) and it seemed to work fine, e.g. called exactly once unless you rotate the screen.

It's quite possible that there are issues with Anvil's config(), but I'm trying to understand their nature:

- It can be an issue with `ViewTreeObserver` - it might call its listener multiple times at no reason.
- It can be an issue with SimpleAttrNode class inside config() binding, e.g. it might call ConfigListener callbacks without need
- It can be an issue with Anvil, so equals() will not work as expected and AttrNode will be evaluated multiple times.

It would help if you give some hints of which case from the above you have there.

**Comment by zserge** [comment] 2015-07-27 16:35
In fact this might be an expected behavior :)

Since you're using Kotlin - most likely you use lambdas as listeners, so on each render cycle a new lambda is created. Right?

Next, config() returns a simpleattrnode, which will be applied only if the config() argument has been changed. Since you generate new lambdas every time - they do change from one Anvil.render() to another. Finally, Anvil.render() is called in every UI event binding like onClick, and it's called on startup at least once per Renderable.

The only surprise then is why ongloballayout is called when no layout changes happen...

**Comment by corbt** [comment] 2015-07-27 16:38
Ah yeah, that makes a lot of sense. I'll test that by replacing the lambda with a named function.

Unfortunately in the process of switching my project from the jcenter release to a local checkout of Anvil I borked my project configuration, and am still trying to get Gradle/Android Studio happy with me again, but I'll report back once I've got that tested. :)

**Comment by zserge** [comment] 2015-07-27 17:10
Btw, I'm now releasing Anvil a few times a day as I write samples and fix issues. Version 0.0.11 will be in a few minutes, so probably just use 'co.trikita:anvil:+' in your gradle configs. I'm not sure, but maybe you can do 'gradle install' to publish your local Anvil copy to the local maven repo, I haven't tried it.

**Comment by corbt** [comment] 2015-07-28 11:34
Just a quick update: I've replaced the lambda with a named function declared outside the anvil tree and it's still getting called multiple times in the same way. Just for reference, here is the relevant excerpt from my `onCreate` method. As a sanity check I've also made sure that `onCreate` itself is only being called once, which it is. But the "sv is $sv" debug log is being hit 4 times at startup, and then again at unpredictable times including most user interactions.

```kotlin
        val setCamera: ((View) -> Unit) = { sv ->
            Log.d(TAG, "sv is $sv")
            actions = camera.startPreview((sv as SurfaceView).getHolder())
        }

        setContentView(object: RenderableView(this) {
            override fun view(): Nodes.ViewNode? {
                return v<RelativeLayout> {
                    v<SurfaceView> {
                        -config(setCamera)
                    }
```

**Comment by corbt** [comment] 2015-07-28 12:07
Ok, I have some new debugging information related to this issue. You can find the debugging information and logs below. I'm looking through the logs myself as well, but maybe something will stick out to you based on your understanding of Anvil.

```kotlin
// TakePicture.kt
// in onCreate
        Log.d(TAG, "beginning anvil rendering")
        val setCamera: ((View) -> Unit) = { sv ->
            Log.d("config", "calling configured method")
            actions = camera.startPreview((sv as SurfaceView).getHolder())
        }

        setContentView(object: RenderableView(this) {
            override fun view(): Nodes.ViewNode? {
                return v<RelativeLayout> {
                    v<SurfaceView> {
                        Log.d("config", "rendering SurfaceView")
                        -config(setCamera)
                    }
```

```java
// BaseAttrs.java
	public static AttrNode config(final ConfigListener listener) {
		Log.d("config", "calling config()");
		return new SimpleAttrNode(listener) {
			private ViewTreeObserver observer(View v) {
				Log.d("config", "calling SimpleAttrNode.observer()");
				return ((ViewGroup) v.getParent()).getViewTreeObserver();
			}
			public void apply(final View v) {
				observer(v).addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
					@Override
					public void onGlobalLayout() {
						Log.d("config", "calling onGlobalLayout()");
						listener.onConfig(v);
						observer(v).removeGlobalOnLayoutListener(this);
						Anvil.render();
					}
				});
			}
		};
	}
```

```java
// Anvil.java
	public static void render() {
		Log.d("config", "Calling render()");
```

```
07-28 13:06:32.879  29267-29267/? D/com.emberall.kiosk.activity.NewTakePicture﹕ beginning anvil rendering
07-28 13:06:33.106  29267-29267/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:06:33.107  29267-29267/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:06:33.108  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:06:33.185  29267-29267/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:06:33.185  29267-29267/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:06:33.186  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:06:33.186  29267-29267/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:06:33.196  29267-29267/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:06:33.196  29267-29267/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:06:33.196  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:06:33.217  29267-29267/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:06:33.217  29267-29267/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:06:33.234  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:06:33.234  29267-29267/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:06:33.262  29267-29267/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:06:33.262  29267-29267/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:06:33.262  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:06:33.598  29267-29267/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:06:33.598  29267-29267/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:06:33.601  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:06:33.601  29267-29267/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:06:33.625  29267-29267/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:06:33.625  29267-29267/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:06:33.625  29267-29267/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
```

**Comment by zserge** [comment] 2015-07-28 12:35
That's interesting. Could you please also add a log right in `apply(View)` right before `observer(v).addOnGlobalLayoutListener`, so we could see wheather it's the same observer or the new one? In your case there should be only one observer created, since the listener remains the same and apply() should be called only once.

**Comment by corbt** [comment] 2015-07-28 12:41
Sure

```
07-28 13:40:49.119  11134-11134/? D/config﹕ rendering SurfaceView
07-28 13:40:49.119  11134-11134/? D/config﹕ calling config()
07-28 13:40:49.121  11134-11134/? D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:49.200  11134-11134/? D/config﹕ calling onGlobalLayout()
07-28 13:40:49.200  11134-11134/? D/config﹕ calling configured method
07-28 13:40:49.201  11134-11134/? D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:49.201  11134-11134/? D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:49.201  11134-11134/? D/config﹕ Calling render()
07-28 13:40:49.214  11134-11134/? D/config﹕ rendering SurfaceView
07-28 13:40:49.214  11134-11134/? D/config﹕ calling config()
07-28 13:40:49.214  11134-11134/? D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:49.227  11134-11134/? D/config﹕ calling onGlobalLayout()
07-28 13:40:49.227  11134-11134/? D/config﹕ calling configured method
07-28 13:40:49.267  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:49.267  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:49.267  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:49.286  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:49.286  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:49.287  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:49.794  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:49.794  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:49.795  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:49.795  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:49.795  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:49.826  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:49.826  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:49.826  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:51.596  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:51.596  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:51.597  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:51.597  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:51.597  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:51.618  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:51.619  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:51.619  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:51.669  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:51.669  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:51.671  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:51.671  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:51.671  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:51.693  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:51.693  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:51.693  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:52.739  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:52.739  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:52.743  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:52.743  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:52.743  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:52.769  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:52.769  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:52.770  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:52.837  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:52.837  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:52.839  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:52.839  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:52.839  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:52.862  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:52.862  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:52.862  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:53.155  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:53.155  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:53.158  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:53.159  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:53.159  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:53.189  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:53.189  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:53.189  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:53.223  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:53.223  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:53.223  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:53.223  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:53.223  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:53.248  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:53.248  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:53.248  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:53.692  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:53.692  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:53.693  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:53.693  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:53.693  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:53.715  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:53.715  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:53.715  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:54.093  11134-11134/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:40:54.093  11134-11134/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:40:54.094  11134-11134/com.emberall.kiosk.local D/config﹕ about to call removeGlobalOnLayoutListener
07-28 13:40:54.094  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:40:54.094  11134-11134/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:40:54.115  11134-11134/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:40:54.115  11134-11134/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:40:54.115  11134-11134/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
```

**Comment by corbt** [comment] 2015-07-28 12:46
Here's a new log where I log the identity of `this`. Interestingly it looks like each call is with a new instance of `BaseAttrs`, don't know if that's expected or not.

```
07-28 13:44:16.959  13202-13202/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:44:16.959  13202-13202/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:44:16.970  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:17.069  13202-13202/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:44:17.069  13202-13202/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:44:17.071  13202-13202/com.emberall.kiosk.local D/config﹕ Observer: trikita.anvil.BaseAttrs$10$1@12adb29c
07-28 13:44:17.071  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:17.071  13202-13202/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:44:17.073  13202-13202/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:44:17.073  13202-13202/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:44:17.073  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:17.103  13202-13202/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:44:17.103  13202-13202/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:44:17.121  13202-13202/com.emberall.kiosk.local D/config﹕ Observer: trikita.anvil.BaseAttrs$10$1@6d4da46
07-28 13:44:17.121  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:17.121  13202-13202/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:44:17.126  13202-13202/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:44:17.126  13202-13202/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:44:17.126  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:17.726  13202-13202/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:44:17.726  13202-13202/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:44:17.728  13202-13202/com.emberall.kiosk.local D/config﹕ Observer: trikita.anvil.BaseAttrs$10$1@d7309c9
07-28 13:44:17.728  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:17.728  13202-13202/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:44:17.755  13202-13202/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:44:17.755  13202-13202/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:44:17.755  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:19.728  13202-13202/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:44:19.728  13202-13202/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:44:19.729  13202-13202/com.emberall.kiosk.local D/config﹕ Observer: trikita.anvil.BaseAttrs$10$1@e48a037
07-28 13:44:19.729  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:44:19.729  13202-13202/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:44:19.733  13202-13202/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:44:19.733  13202-13202/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:44:19.734  13202-13202/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
```

**Comment by corbt** [comment] 2015-07-28 12:49
I've deleted the last two messages because I don't think they were what you were asking for. Here is the debug output with the identity of the actual observer (`Log.d("config", "Observer: "+observer(v));`), which appears not to change:

```
07-28 13:48:34.717  15855-15855/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:48:34.717  15855-15855/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:48:34.722  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:34.816  15855-15855/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:48:34.817  15855-15855/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:48:34.821  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:34.821  15855-15855/com.emberall.kiosk.local D/config﹕ Observer: android.view.ViewTreeObserver@18c3b934
07-28 13:48:34.821  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:34.821  15855-15855/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:48:34.822  15855-15855/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:48:34.822  15855-15855/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:48:34.822  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:34.853  15855-15855/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:48:34.853  15855-15855/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:48:34.867  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:34.867  15855-15855/com.emberall.kiosk.local D/config﹕ Observer: android.view.ViewTreeObserver@18c3b934
07-28 13:48:34.867  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:34.867  15855-15855/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:48:34.868  15855-15855/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:48:34.868  15855-15855/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:48:34.868  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:35.228  15855-15855/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:48:35.228  15855-15855/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:48:35.231  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:35.231  15855-15855/com.emberall.kiosk.local D/config﹕ Observer: android.view.ViewTreeObserver@18c3b934
07-28 13:48:35.231  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:35.231  15855-15855/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:48:35.249  15855-15855/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:48:35.249  15855-15855/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:48:35.249  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:37.006  15855-15855/com.emberall.kiosk.local D/config﹕ calling onGlobalLayout()
07-28 13:48:37.006  15855-15855/com.emberall.kiosk.local D/config﹕ calling configured method
07-28 13:48:37.012  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:37.012  15855-15855/com.emberall.kiosk.local D/config﹕ Observer: android.view.ViewTreeObserver@18c3b934
07-28 13:48:37.012  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
07-28 13:48:37.012  15855-15855/com.emberall.kiosk.local D/config﹕ Calling render()
07-28 13:48:37.013  15855-15855/com.emberall.kiosk.local D/config﹕ rendering SurfaceView
07-28 13:48:37.013  15855-15855/com.emberall.kiosk.local D/config﹕ calling config()
07-28 13:48:37.013  15855-15855/com.emberall.kiosk.local D/config﹕ calling SimpleAttrNode.observer()
```

**Comment by zserge** [comment] 2015-07-28 13:01
This is really strange. I've made a quick app hoping to get the same isue, but no, I only get onConfig() called once. Here's the sources (all app in one class) - https://gist.github.com/zserge/4d3ba482645151e79a5b

**Comment by zserge** [comment] 2015-07-28 13:05
Regarding your logs, probably we misunderstood each other.

I need log messages like:
```
 public static AttrNode config(final ConfigListener listener) {
        Log.d("config", "config(): listener=" + listener); // Is listener the same each time?
        return new SimpleAttrNode(listener) {
            private ViewTreeObserver observer(View v) {
                Log.d("config", "observer(): view="+ v); // Do we work with the same view?
                return ((ViewGroup) v.getParent()).getViewTreeObserver();
            }
            public void apply(final View v) {
                Log.d("config", "apply(): view=" + v); // How many times apply is called, it should be lazy and called only once
                observer(v).addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                        Log.d("config", "onConfig(): view="+v); // Finally, how many times our callback is fired
                        listener.onConfig(v);
                        Log.d("config", "removeGlobalOnLayoutListener(): listener="+this); // Listeners should be all cleaned up
                        observer(v).removeGlobalOnLayoutListener(this);
                        Anvil.render();
                    }
                });
            }
        };
}
```

**Comment by corbt** [comment] 2015-07-28 13:43
Working backwards from your gist, I was able to get the observer working as expected.

It appears that the issue is that Kotlin generates a new instance of the interface implementation class (ConfigListener) on each call, even if a named, immutable function reference is used instead of a lambda. My current workaround is to create an implementation of the ConfigListener interface explicitly instead of using either an anonymous or named function. This fixes the problem for now.

```kotlin
        // this works
        val config = object : ConfigListener {
            override fun onConfig(v: View) {
                println("onConfig(): v=" + v)
                actions = camera.startPreview((v as SurfaceView).getHolder())
            }
        }
```

**Comment by zserge** [comment] 2015-07-28 13:58
I think should be possible to come up with some binding like `once(tag, value)`. Basically it will take a value, return the same value and keep it in the tag. Next time it's called - the new value is passed but the old value from the tag is be returned. This might be handy for lambdas (of course new lambda objects will still be created, but they will be GC'ed immidiatelly.

**Comment by zserge** [comment] 2015-07-28 17:24
@corbt Have a look at the recent commit. I've added `once(val)` helper, a super simple hack/workaround - it returns AttrNode only on the first rendering cycle. Which means using it like:

```
v(View.class,
  once(config(v -> .....)));
```

will create new config listeners every time (that's unavoidable I think), but only the first one will be applied to the view.

**Comment by corbt** [comment] 2015-07-28 19:21
I run into errors with this helper, presumably related to the fact that it's returning `null` where a node is expected.

Top of the stack trace:

```
E/ExceptionReporter( 6616): java.lang.NullPointerException: Attempt to invoke interface method 'void trikita.anvil.Nodes$AttrNode.apply(android.view.View)' on a null object reference
E/ExceptionReporter( 6616): 	at trikita.anvil.Anvil.inflateNode(Anvil.java:249)
E/ExceptionReporter( 6616): 	at trikita.anvil.Anvil.inflateNode(Anvil.java:233)
E/ExceptionReporter( 6616): 	at trikita.anvil.Anvil.render(Anvil.java:106)
```

**Comment by zserge** [comment] 2015-07-28 19:39
Ah, right, I forgot that in Kotlin the tree construction process happens a bit differently. Yeah, probably I shall remove that `once` hack, now it looks very bad to me. Maybe limiting `config()` binding to be effective only before the view is rendered would make sense.

**Comment by zserge** [comment] 2015-07-28 20:50
@corbt How about changing the config() binding to:
```
	public static AttrNode config(final ConfigListener listener) {
		return new SimpleAttrNode(null) {
		....
```

Since the value is constant - the node will be applied only when the previous node is null, which is on the first rendering. Can you please try it with your old code (when config listener was re-created)?

**Comment by corbt** [comment] 2015-07-29 09:58
Yes, I confirm that changing the argument of SimpleAttrNode to null causes it to be called only on the first rendering, even when passed a kotlin lambda.

For my use case this would be a fine fix, because I can't think of a situation where I would want config() to be called more than once when the element is first rendered. I'm not sure if there are use cases where that would be important though.

**Comment by zserge** [comment] 2015-07-29 10:22
Great, check the most recent commit and version 0.0.12 on jcenter/mavencentral. If that works for you - I'll close this.

**Comment by corbt** [comment] 2015-07-29 10:39
Yep, working!

**Closed** 2015-07-29 10:50 UTC
