### ISSUE TITLE
Manually getting a view

### ISSUE THREAD

**Issue by corbt** [zserge/anvil#16] opened 2015-05-30 16:18 UTC
Ok, so I need to manually get a view from a layout managed by Anvil. I have a TextureView that I need to hook up to the camera. The view I need is always visible in the activity, so Anvil should always render it. Currently what I'm trying is based on a technique described [here](http://stackoverflow.com/questions/8937380/how-to-set-id-of-dynamic-created-layout):

```kotlin
v<AutoFitTextureView> {
    -size(FILL, 400)
    -id(R.id.camera_preview)
}
```

And then later on, still within `onCreate`:

```kotlin
mTextureView = findViewById(R.id.camera_preview) as AutoFitTextureView
```

but Android isn't able to find the view (`findViewById` returns null). Is there a better way to capture a reference to a view object than what I'm doing here? I think the ideal would be to implement something similar to React's [refs](https://facebook.github.io/react/docs/more-about-refs.html), but I'd be happy with a workaround.

**Comment by zserge** [comment] 2015-05-30 18:57
I don't remember exactly, but can you try doing findViewById inside the onAttachedToWindow()?

**Comment by corbt** [comment] 2015-05-30 19:03
It looks like I run into the same issue when I put it there.

```kotlin
    override fun onAttachedToWindow() {
        super.onAttachedToWindow()

        println(findViewById(R.id.camera_preview).javaClass.getName())
    }
```

Throws the error `Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference`

**Comment by zserge** [comment] 2015-05-30 19:14
Ok. Can you try `onMeasure()`? It's the callback where the RenderableView is normally rendered for the first time.

**Comment by zserge** [comment] 2015-05-30 19:21
Ah, I found it.
In fact I did the post() inside the onAttachedToWindow() and there in a Runnable I called findViewById.

**Comment by zserge** [comment] 2015-05-30 19:23
The idea with refs is really interesting.
So we have AttrNode generators like text(), onClick() etc. Each of then has the actual View instance when called. Which means each of them can actually cache it somewhere.
The problem is that we can't pass the reference, e.g. `ref(mMyView)` and expect that the view instance will be assigned to mMyView.

**Comment by zserge** [comment] 2015-06-01 06:47
If you look at v15.Attrs class you may find `onMount()` and `onUnmount()` functions.
Each of them takes a listener that is called whenever the view is attached or detached from the layout.
You can configure the view inside that listener, or you may just remember it's reference.

E.g

``` java
OnMountListener mOnMountListener = new OnMountListener() {
  public void onMount(View v) {
    // Setup your view here
  }
};

v(FrameLayout.class,
  v(Button.class,
    onMount(mOnMountListner)));
```

**Comment by corbt** [comment] 2015-06-01 09:09
I haven't been able to get onMount to work properly (the callback is never fired). I did build some experimental support for refs in that I'm currently using which you can see in the related PR, but the major blocker is still that I haven't found a callback/lifecycle event that is triggered when the views are fully rendered, and so I'm limited to just using a timeout-based system, which is ugly and may be unreliable especially on slower hardware. `onMount` could be used to fix that issue, but like I said, I can't get it to trigger.

**Comment by zserge** [comment] 2015-06-01 20:30
I have seen you PR, and I like its simplicity. But I personally prefer having something similar to onMount instead of refs. The main reasons are:

- Using strings as View IDs is a bit fragile (no compiler errors if you mistype). Using R.id.something is too ugly to my mind.
- Storing views in some external collection may result in view leaks. WeakHashMap can be a solution, but that complicates things. Keeping the collection inside a RenderableView is too implicit, and would not work for other Renderables (Activities, Fragments).
- Anvil inclines you to not use View IDs at all, instead control views by virtual AttrNode generators (standard or custom ones). I agree that in some cases manipulating real views is unavoidable. But I'm afraid there will be a small chance when one needs a big list of views to configure manually. I think it would rather be one or two per project.

I confirm that current onMount/onUnmount don't work. However, here's a possible solution that works on API level 1 using the ViewTreeObserver:

``` java
public interface ConfigListener {
	public void onConfig(View v);
}

public static AttrNode config(final ConfigListener listener) {
	return new SimpleAttrNode(listener) {
		public void apply(final View v) {
			final ViewTreeObserver obs = ((ViewGroup) v.getParent()).getViewTreeObserver();
			obs.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
				public void onGlobalLayout() {
					listener.onConfig(v);
					obs.removeGlobalOnLayoutListener(this);
				}
			});
		}
	};
}
```

It mimics the `config()` function in Mithril, which is used to solve a similar problem, e.g. to access the real DOM element instead of a virtual one - http://lhorie.github.io/mithril/mithril.html#accessing-the-real-dom-element

What do you think of it?

**Comment by corbt** [comment] 2015-06-02 09:42
Ok yeah, that seems like a good solution. Will `onConfig` be called on each rerender, or only when the view is first created/changed?

**Comment by zserge** [comment] 2015-06-02 10:02
The snippet I've sent above calls `onConfig` just once (then it removes the layout listener), so it won't be triggered when next child is inserted. I don't think there is much sense in a callback that is called on each rendering cycle because, well, `Renderable.view()` is called on each rendering cycle anyway so you can use that.

**Comment by corbt** [comment] 2015-06-02 10:05
What about the case where you change the state so the view is removed, and then change it again so the view comes back? Will the callback be called the second time?

**Comment by zserge** [comment] 2015-06-02 10:42
Just tested it, when the view is added after it has been removed - `onConfig` is fired again.
Basically, this works well enough when you need to manually configure your view, the only drawback is that you can't deinitialize your view in the same manner. The only way I see is to use `onDetachedFromWindow` in the parent RenderableView to clean up everything.

**Comment by corbt** [comment] 2015-06-02 11:51
Ok. It would be ideal to have a callback that's invoked when a view is about to be cleaned up, but in the use case I'm worried about right now (removing a video preview from the view once a video has been recorded successfully) I can predict when that's going to happen and just do the necessary cleanup somewhere else before Anvil's re-rendering is called. So the config solution will work well for me.

**Comment by zserge** [comment] 2015-06-14 16:09
I've added the `config()` helper for the `BaseAttrs`, so configuring the views manually is now possible.
Regarding undoing the configuration - it seems to be impossible with any of the standard android APIs. The only way I see it can be done is in the parent RenderableView's `onDetachedFromWindow()`.

I'm closing this, and @corbt , don't you mind if I reject your pull request in favor of using `config()`?

**Closed by zserge** 2015-06-14 16:09 UTC

**Comment by corbt** [comment] 2015-06-15 14:08
Yeah, I don't mind if you reject the pull request. I'll test later to see whether this `config` works for my needs. I tried it earlier when you first posted it, and wasn't able to get it working for what I needed to do, but it has been long enough now that I can't remember what the problem was (maybe it was getting called more than once when the view hadn't actually updated? but I don't remember). I'll let you know if I have trouble with it.
